### ISSUE TITLE
Got following dependency conflicts on Mac

### ISSUE THREAD

**Issue by arora-manish** [Redislabs-Solution-Architects/document-lookaside#1]
On Mac

$ pip install -r requirements.txt

Got following dependency conflicts: 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.27 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
conda-repo-cli 1.0.27 requires nbformat==5.4.0, but you have nbformat 5.5.0 which is incompatible.

**Comment by joeywhelan** [comment]
Python conflicts corrected.

**Comment by joeywhelan** [comment]
Python conflicts corrected.
